modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
issueTrackerURL="https://github.com/Electrolyte220/Unstable/issues"
[[mods]]
modId="unstable"
version="${file.jarVersion}"
displayName="Unstable"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://curseforge.com/minecraft/mc-mods/unstable-mod"
#logoFile="examplemod.png" #optional
credits="RWTema for making Extra Utilities"
authors="Electrolyte"
description="Adds the Unstable Tools & Rituals from Extra Utilities 1."

[[dependencies.unstable]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.unstable]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
